# This script parse energy results from the ouput files generated by get_energy.sh 
# and print the lower one (best one) for each file. 

import os, sys
from os import listdir
from os.path import isfile, join


def main(file):
    best_scores = {}
    fileh = open(file, 'r+')
    lines = fileh.readlines()
    lines = [l.rstrip('\n') for l in lines]
    for l in lines:
        path, val = l.split(':')
        id = path.split('/')[3]
        if id not in best_scores.keys():
            best_scores[id] = [path, val]
        else:
            if val < best_scores[id][1]:
                best_scores[id] = [path, val]

    return best_scores

def print_scores(best_scores):
    open_out = open('models_best_scores.txt', 'w')
    for k, v in best_scores.items():
        message = "%s\t%s\n" %(k, v[0])
        open_out.write(message)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print "\n Please use template.ID as an argument. e.g.: $lower_energy.py energy_file.txt\n"
    file = sys.argv[1]

best_scores =  main(file)
print_scores(best_scores)